### ISSUE TITLE
Add config manager

### ISSUE THREAD

**Issue by dreulavelle** [dreulavelle/Anchor#1]
Need to handle config file along with user paths to mount points and what not. Currently this is being done as an environment variable for the mount paths to make things simple.

Docker Compose related lines..
```yml
    volumes:
      - /mnt/rclone:/mnt/rclone
      - /mnt/symlink:/mnt/symlink
    environment:
      - MDB_API_KEY=apikeyapikeyapikey    # MDBList API Key Required!
      - RCLONE_DIR=/mnt/rclone            # Source Directory
      - SYMLINK_DIR=/mnt/symlink          # Destination Parent Directory
 ```
